fix example\c_wrapper\c_uni.c(610,12): error C2198: 'impl_norm_is_nfc_utf8' et al: too few arguments for call: missing third parameter `bool check_stream_safe`